const message = [
    "Oh, hey. You're here.",
    "Well, 's not too late to change tabs. But if you must, do expect a minor repercussion to burst out of your screen.",
    "Just kidding. I know how much you adore surprises.",
    "Anyway, where do I even start?",
    "Right. First off…",
    "There is no first. Because everything you've done for me—for all of us—can hardly be arranged in an order. Or squeezed, crammed into a small sequential log.",
    "I mean, technically, I could. But I'm not about to list your deeds in bullets like a shopping list.",
    "This isn't about efficiency. It's about, uh… pouring one's heart and soul…",
    "Whatever sickening Christmas idiom every jolly good fellow says. You get the point.",
    "But, thank you. Thank. You. For every call you've taken, every shift you've finished. Every OT streak and workplace (and personal) bullshit that you had to endure.",
    "For every hour you spent bending your back over the desk for your boss…",
    "Boss' dues. The, er, monetary kind.",
    "Anyone could have keeled over from the burden of sustaining three adult idiots in a dysfunctional home and flew off to Tahiti, the island of dreams.",
    "But you didn't. You never gave up on us, or yourself.",
    "When I once described you as 'passive', or placid, I was shortsighted; never truly perceiving the depths of your resolve.",
    "I honestly don't know how you still do it, up to this day. That firm, yet gentle kindness you freely hold and give.",
    "Maybe I never will. An indecipherable sage secret, eh? Perhaps it is, to a fastidious prick like me. ✨",
    "And with texts of gratitude comes a sincere, honest-to-god apology:",
    "I am sorry.",
    "No sarcasm there, I assure you. Although I wouldn't blame you if you mistook it for a joke.",
    "I know your ears have strained, time and time again, from hearing that phrase come out of my lying mouth.",
    "For a decade, I didn't know how other humans worked. How I worked. So I turned you into two things: emotional soundboard and luggage carrier.",
    "Nobody should ever have to be either. Nobody.",
    "And the times I plucked at your flaws, stabbing you verbally with reckless abandon… I reflected the very hatred I received from others. And ones I afflicted upon myself.",
    "I know now, I was wrong. Stupid wrong. I never want a repeat of that old, toxic siblingship ever again.",
    "I do know and love myself a little better now. Why, instead of a walking encyclopedia, I 'strut' now. With my beloved boots, to boot. Fuck that one guy who broke up with me cause he couldn't handle it. ✨",
    "Once more, I say my thanks. You've supported me every step of the way. You are the best, most wholesome nerd/geek to have ever brothered. Yes, it's a verb now. I declare it.",
    "I hope you love yourself, too. That one is really important. Like, real love, okay? Not the fake, confident bravado people wear on their sleeves.",
    "Now, you see why I can't tell you all this in person? If I am to execute a speech, it better be genuine OR sad. 'OR'. It can't be both.",
    "So, remember when I asked you a survey of a random wild animal? I did the same with two other friend groups of mine.",
    "A majestic plume of white feathers that soar the sky. The kingly tusks of a water-dwelling bull. Squirming curls on an eyeball propelling aimlessly throughout the sea.",
    "An amalgamation born from the unholy communion of an eagle, walrus, and squid. It's been a long while since I drew, but I did my best.",
    "To those who have lent me their prowess in defeating this evil giant. I will forever remember your names, as they have been engraved on your spears and rocks.",
    "Here's the link:",
    "https://drive.google.com/file/d/1pXNd6ahGwxquwE7vEwfl8mWXA27sHlhn/view?usp=sharing",
    "Now, go on. Shoo. Don't talk to me about this after. It's much too sickly sentimental for my liking.",
];

export default message 